Switch the public registry hostname depends on tfExecType
The state replace-provider command returns the following error when
using a legacy terraform state in tofu.

```
tofu state replace-provider registry.terraform.io/-/null registry.terraform.io/hashicorp/null

Error: Invalid "from" provider "registry.terraform.io/-/null"

Invalid provider namespace: The legacy provider namespace "-" can be used
only with hostname registry.opentofu.org.
```